### ISSUE TITLE
`let` styling doesn't match `var`, `const`

### ISSUE THREAD

**Issue by elbeezy** [subtleGradient/language-javascript-jsx#12]
![screen shot 2015-09-09 at 3 11 38 pm](https://cloud.githubusercontent.com/assets/1879691/9771582/23f2b410-5705-11e5-8f5d-4236dc077873.png)

**Comment by SC7639** [comment]
+1

**Comment by subtleGradient** [comment]
I have an update in the works for let, const, and type

**Comment by SC7639** [comment]
Ok brilliant! I've added it in the mean time to my own manually

**Comment by davidhariri** [comment]
Status on this?

**Comment by subtleGradient** [comment]
Fixed in the upstream, but I haven't synced changes down recently. I'll try to get to that soon. Sorry for the delay

**Comment by onedr0p** [comment]
+1

@subtleGradient please update this, I know you haven't been active in months, but when you get the time, please find the time to update.

**Comment by lyquocnam** [comment]
![let-keyword](https://cloud.githubusercontent.com/assets/8347826/13371952/eaf14a0a-dce7-11e5-962b-f308980fe2fc.PNG)

let keyword still not style...

**Comment by benpptung** [comment]
I can confirm `let` styling is an issue, and this is what I see via Developer tool.

Before this package was installed. The hierarchy classes in a line:

#### classes for const
```
syntax--source syntax--js
	syntax--storage syntax--type syntax--const syntax--js
```

#### classes for variable following const
```
syntax--source syntax--js
	syntax--constant syntax--other syntax--js
```

#### classes for let
```
syntax--source syntax--js
	syntax--meta syntax--method-call syntax--js
		syntax--meta syntax--arguments syntax--js
			syntax--storage syntax--type syntax--var syntax--js
```

#### classes for variables following let
```
syntax--source syntax--js
	syntax--meta syntax--method-call syntax--js
		syntax--meta syntax--arguments syntax--js
```

After this package installed:

#### classes for const
```
syntax--source syntax--js syntax--jsx
	syntax--storage syntax--modifier syntax--js
```

#### classes for variable following const
```
syntax--source syntax--js syntax--jsx
	syntax--variable syntax--other syntax--readwrite syntax--js
```

#### classes for let
```
syntax--source syntax--js syntax--jsx
	syntax--variable syntax--other syntax--readwrite syntax--js
```

#### classes for variables following let
```
syntax--source syntax--js syntax--jsx 
	syntax--variable syntax--other syntax--readwrite syntax--js
```

After this package installed, I tried to style `let`, however, based on the above classes, it seems not possible to distinguish `let` from the variable following `let`, because they are with same classes.

**Comment by subtleGradient** [comment]
Thanks for looking into this, but I'm not able to fix it at this time. I
recommend uninstalling the package and using one of the better maintained
packages instead. Sorry for the hassle
